# docker-compose.yml
version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=unicorn
        - MONGO_INITDB_ROOT_PASSWORD=fairydust
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
  python-application:      
    image: beanie-py
    container_name: py-app
    volumes:
      - ./src:/app
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=unicorn
      - ME_CONFIG_MONGODB_ADMINPASSWORD=fairydust
      - ME_CONFIG_MONGODB_URL=mongodb://unicorn:fairydust@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"